spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miaosha?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.kalo.entity
